from autopr.models.rail_objects import RailObject


# class GeneratedCodeLine(RailObject):
#     """
#     A line of code that has been generated by the codegen agent.
#     Contains a granular representation of the line of code, for lesser ambiguity.
#     This representation is very token-heavy, but may increase accuracy.
#     TODO try this if a normal string doesn't work well
#     """
#     output_spec = """<integer
#     name="line_num"
#     description="The line number of the line of code."
#     format="positive"
#     required="true"
#     on-fail="noop"
# />
# <integer
#     name="indent"
#     description="The number of space characters used for indentation."
#     required="true"
# />
# <string
#     name="content"
#     description="Content of the code line, stripped of leading whitespace."
#     required="true"
#     format="no-leading-whitespace"
#     on-fail-no-leading-whitespace="fix"
# />"""
#
#     line_num: int
#     indent: int
#     content: str
#
#
# class GeneratedCodeHunk(RailObject):
#     """
#     A hunk of code that has been generated by the codegen agent, as a list of lines with metadata.
#     """
#     output_spec = f"""<list
#     name="lines"
#     description="The lines of code in the hunk."
#     required="true"
# >
# <object>
# {GeneratedCodeLine.output_spec}
# </object>
# </list>"""
#
#     lines: list[GeneratedCodeLine]


class RewrittenFileHunk(RailObject):
    """
    A hunk of code that has been generated by the codegen agent.
    """
    output_spec = """<string
    name="contents"
    description="The raw rewritten contents of the hunk."
    required="true"
/>
<string
    name="outcome"
    description="A description of the outcome of the attempt to rewrite the file hunk according to the problem statement." 
    required="true"
/>"""

    contents: str
    outcome: str


class NewFileHunk(RailObject):
    """
    A new file that has been generated by the codegen agent.
    """
    output_spec = f"""<string
    name="contents"
    description="The raw contents of the new file."
    required="true"
/>
<string
    name="outcome"
    description="A description of the outcome of the attempt to generate the file according to the problem statement." 
    required="true"
/>"""

    contents: str
    outcome: str
