# TODO: PART1: THIS SHOULD GET RETURNED
#   PART2: THIS SHOULD GET RETURNED

# TODO: PART1:this is whatever
# PART2: HIS SHOULDN'T GET RETURNED

# TODO: PART1: THIS SHOULD GET RETURNED
#   PART2: THIS SHOULD GET RETURNED